version: '3'

services:
    db: 
        build: 
            context: mysql
        command: --innodb-use-native-aio=0
        container_name: mysqldb
        restart: always
        tty: true
        volumes: 
            - ./mysql/data:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - nodenw

    nodeapp: 
        build:
            context: node
        container_name: nodeapp
        # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        restart: always
        tty: true
        volumes: 
            - ./node:/usr/src/app
        networks: 
            - nodenw
        depends_on: 
            - db
        # ports:
        #     - "3000:3000"

    nginx: 
        build: 
            context: nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8080:80"
        networks: 
            - nodenw
        depends_on: 
            - nodeapp

networks: 
    nodenw:
        driver: bridge